language: node_js
node_js:
  - node
cache:
  yarn: true
branches:
  only:
    - master
script:
  - yarn build
after_script:
  - yarn start-int-tests-server
  - yarn test-e2e
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true