language: node_js
node_js:
  - node
cache: npm
branches:
  only:
    - master
build:
  - npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true